---
- name: simple
  hosts: all
  gather_facts: false
  tasks:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
    - argtest:
...
